# Generated by Django 5.1.2 on 2024-10-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Employer',
            new_name='ProfileEmployer',
        ),
    ]
