# Generated by Django 5.1.2 on 2024-10-22 10:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_review_name_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileemployer',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='siterating',
            options={'verbose_name': 'Рейтинг сайта', 'verbose_name_plural': 'Рейтинг сайта'},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'ЗАВЕРШЕНО'), ('not_complete', 'НЕ ЗАВЕРШЕНО')], default='not_complete', max_length=12)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('services', models.ManyToManyField(to='mainapp.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
    ]
