# Generated by Django 5.1.2 on 2024-10-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_profileemployer_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-status'], 'verbose_name': 'Запись на прием', 'verbose_name_plural': 'Записи на прием'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time_after_break',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
