# Generated by Django 5.1.2 on 2024-10-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
    ]
