# Generated by Django 5.1.2 on 2024-10-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_appointment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mom_site/mainapp/static/mainapp/images'),
        ),
    ]
