# Generated by Django 5.1.2 on 2024-10-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
