# Generated by Django 5.1.2 on 2024-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('manicure', 'маникюр'), ('pedicure', 'педикюр'), ('face', 'лицо')], default='manicure', max_length=40),
        ),
    ]
