# Generated by Django 5.1.2 on 2024-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('manicure', 'маникюр'), ('pedicure', 'педикюр'), ('face', 'лицо'), ('piling', 'пилинг')], default='manicure', max_length=40),
        ),
    ]
