# Generated by Django 5.1.2 on 2024-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='note_service',
            field=models.TextField(blank=True),
        ),
    ]
