# Generated by Django 5.1.3 on 2024-12-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_review_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.DurationField(default='00:00'),
        ),
    ]
