# Generated by Django 5.1.3 on 2025-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_appointment_last_name_appointment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotAvailaibleDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
