# Generated by Django 5.1.3 on 2025-01-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_notavailaibledates_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
    ]
