# Generated by Django 5.1.3 on 2025-01-25 14:40

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_appointment_last_name_remove_appointment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Описание файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
            managers=[
                ('obj_video', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='залупа', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='залупа', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default='отсутствует', max_length=11),
        ),
    ]
