# Generated by Django 5.1.3 on 2025-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_videofile_options_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture_user',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
