# Generated by Django 5.1.3 on 2025-01-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_blogpost_blogpostphotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Записи в блоге', 'verbose_name_plural': 'Записи в блоге'},
        ),
    ]
