# Generated by Django 5.1.3 on 2025-01-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostphotos',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogpost'),
        ),
    ]
