# Generated by Django 5.1.3 on 2025-01-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BlogPostComment',
        ),
    ]
