# Generated by Django 5.1.3 on 2025-01-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_blogpostcomment_blog_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коментарии пользователей к записям в блоге', 'verbose_name_plural': 'Коментарии пользователей к записям в блоге'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('type1', 'тип1'), ('type2', 'тип2'), ('type3', 'тип3'), ('type4', 'тип4')], default='type1', max_length=5),
        ),
    ]
