# Generated by Django 5.1.3 on 2025-01-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_blogpostcomment_options_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='type',
        ),
    ]
