"""
Django settings for Beauty_Dom project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import datetime, timedelta, time

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bd)v_r-6vyyibm5nj3m0yn#g3xyrs(=dhxtju3yr0#)l$_i4vv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://7972-176-197-198-140.ngrok-free.app']
# Application definition

INSTALLED_APPS = [
    'adminapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'formtools',
    'background_task',
    'django_cleanup'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
]

ROOT_URLCONF = 'Beauty_Dom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'Beauty_Dom' / 'adminapp' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Beauty_Dom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_mysql',
        'USER': 'rodion',
        'PASSWORD': '12345',
        'HOST': 'localhost',  # Или другой адрес
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Krasnoyarsk'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mainapp/static'),  # Статика приложения mainapp
    os.path.join(BASE_DIR, 'static'),         # Общая статика
    os.path.join(BASE_DIR, 'adminapp/static') # Статика приложения adminapp
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DATETIME_FORMAT = 'Y-m-d H:i'
TIME_FORMAT = 'H:i'

LANGUAGE_CODE = 'ru'

SMSRU_API_KEY = '7FDFD7A6-FA50-D496-B2C3-CE8C7C998832'

MEDIA_URL = '/media/'  # URL для доступа к загруженным файлам
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/') # Папка для загружаемых файлов

LOGOUT_REDIRECT_URL = '/'  # Перенаправление на главную страницу

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Замените на ваш SMTP сервер
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'beautydom42@gmail.com'
EMAIL_HOST_PASSWORD = 'xesk aaxx boeo bjsn'
DEFAULT_FROM_EMAIL = 'Beauty_Dom'

AUTH_USER_MODEL = 'mainapp.CustomUser'

START_WORK = time(9, 0)
END_WORK = time(17, 0)
STEP = timedelta(minutes=15)
BREAK_AFTER_WORK = timedelta(minutes=30)

# Преобразуем время в datetime, используя произвольную дату (например, сегодня)
today = datetime.today()
start_time = datetime.combine(today, START_WORK)
end_time = datetime.combine(today, END_WORK)

# Находим разницу между двумя datetime объектами
WORKDAY_DURATION = end_time - start_time



is_verify =  False




